[profile.default]
src = "src"
out = "out"
libs = ["lib"]
#solc = "0.8.20"
#offline = true  # 强制使用本地编译器
# 启用viaIR来解决stack too deep错误
via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"

# 本地环境配置
[profile.local]
src = "src"
out = "out"
libs = ["lib"]
# 本地环境特定设置
eth_rpc_url = "http://127.0.0.1:8545"
via_ir = true
optimizer = true

# Sepolia测试网配置
[profile.sepolia]
src = "src"
out = "out"
libs = ["lib"]
sepoliaAdmin = "${SEPOLIA_PRIVATE_KEY}"
# Sepolia特定设置
eth_rpc_url = "${SEPOLIA_RPC_URL}"
via_ir = true
optimizer = true
